spring.application.name=lavadero-api
# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/LavaderoAutos
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
